import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import styles from "../styles/Home.module.css";
import { auth } from "../lib/firebase";
import Login from "../components/login";
import { firestore } from "../lib/firebase";
import { getAuth, onAuthStateChanged } from "firebase/auth";
import { collection, doc, getDoc, query, where } from "firebase/firestore";
import { useContext, useEffect, useState } from "react";
import { UserContext } from "../lib/context";
import { useUserData } from "../lib/hooks";
import { uuidv4 } from "@firebase/util";
import { firstore } from "../lib/firebase";
import Link from "next/link";
import { useCollection } from "react-firebase-hooks/firestore";
import {generateX25519Keypair, genereateKeys} from "../lib/e2ee/e2ee"

function Thread(thread) {
    const [threadData, setThreadData] = useState(thread.thread);

    return (
        <Link href={threadData.id ? threadData.id : "/"}>
            <button className={styles.thread}>
                <h1 className={styles.threadTitle}>
                    {threadData.groupName ? threadData.groupName : ""}
                </h1>
            </button>
        </Link>
    );
}

export default function Home() {
    const { user, data } = useContext(UserContext);

    const [threads, setThreads] = useState();

    const [usersThreads, usersThreadsLoading, usersThreadsError] =
        useCollection(
            query(
                collection(firestore, "threadsId"),
                where("members", "array-contains", user && user.uid)
            ),
            {
                snapshotListenOptions: { includeMetadataChanges: true },
            }
        );

    const loadThreads = async () => {
        console.log("started")

        if (!data || !user || !usersThreads) return;
        console.log("here")
        const localThreads = [];
        for (let i in usersThreads.docs) {
            if (!usersThreads.docs[i].data().members.includes(user.uid)) {
                return;
            }
            let docData = (
                await getDoc(doc(firestore, "threads", usersThreads.docs[i].id))
            ).data();
            docData.id = usersThreads.docs[i].id;
            localThreads.push(docData);
        }
        console.log("done");
        localThreads.sort((a, b) =>
            a.latestMessage < b.latestMessage ? 1 : -1
        );
        setThreads(localThreads);
    };

    useEffect(() => {
        loadThreads();
    }, [usersThreads, user, data]);

    if (!user) {
        return <Login />;
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Your Feed</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.threadsContainer}>
                <h1 className={styles.threadsTitle}>Threads</h1>
                {threads &&
                    threads.map((el) => <Thread key={uuidv4()} thread={el} />)}
            </main>
        </div>
    );
}
